export enum ROUTES {
  home = "/",
  customers = "/customers",
  analytics = "/analytics",
  messages = "/messages",
  setting = "/setting",
  help = "/help",
  newCustomer = "/customers/newCustomer",
  newCustomerByFile = "/customers/newCustomerByFile",
  editCustomer = "/customers/editCustomer/:id",
  uploadWrong = "/customers/uploadWrong",
  uploading = "/customers/uploading",
  showCustomer = "/customers/showCustomer/:id",
  login = "/login",
}
